### PR TITLE
feat: first working version simple vesting contract

### PR DESCRIPTION
**Pull request by Jazz877**

### CODE REVIEW

**Comment by Jazz877** [comment]
@borgbob this is a really simple implementation of CW20 Vesting contract for kleo. I did modify the contract in this public repository https://github.com/ben2x4/cw-vest.

I added a RevokePayments Execute message in order to leave the possibility to revoke payments before they are "paid". This could be a form of defense for human errors and etc...
The owner would be a multisig wallet.

I also removed the native payment logic since we don't want to have it on this contract, if we might need it we can deploy an additional contract leaving this simple and CW20 centric.

It is deployed on the testnet uni-3, you can simply query it using https://blueprints.juno.giansalex.dev/#/contracts/juno1c70fycn6ahnekfwgqpplmukvzccyjnl3lq8zcp3j8csyv72jap3qdznt0q

**Comment by borgbob** [comment]
@Jazz877 looking at it. Sorry for the long response time, have been very busy at work.

Do we need to add a query for each vesting wallet balance? I think we will need it to consider vesting balance when calculating votes

**Comment by Jazz877** [comment]
> @Jazz877 looking at it. Sorry for the long response time, have been very busy at work.
> 
> Do we need to add a query for each vesting wallet balance? I think we will need it to consider vesting balance when calculating votes

Take a look to this new implementation of the vesting contract, I guess it already has what we need about vesting balances: https://github.com/Jazz877/kleo-cw20/pull/2

**Comment by Jazz877** [comment]
I am discarding this solution in favour of this https://github.com/Jazz877/kleo-cw20/pull/2 which seems to be more suitable for our goal

**Pull request closed without merging**
